project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: model.qmd
        text: Model       
      - href: analysis.qmd
        text: Analysis           
      - href: source.qmd
        text: Sources
      - about.qmd       
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



