project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: analysis.qmd
        text: Analysis   
      - href: model.qmd
        text: Model        
      - href: source.qmd
        text: Sources
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



